import type { Metadata } from 'next';

import '@/styles/globals.css';

import { inter, londrina } from '@/styles/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable} ${londrina.variable}`}>
      <body>{children}</body>
    </html>
  );
}
